#pragma config(Sensor, in1,    potA,           sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
float batt = 0.0;
float a = 0.0;
float b = 0.0;
float c = 0.0;
float d = 0.0;
float e = 0.0;
float f = 0;
float g = 0;
float q = 0.0;

task main()
{
	/*
	while (true){
		while(vexRT(Btn6U) == false){
			;
		}
		while(vexRT(Btn6U) == true){
			;
			motor[port2] = vexRT(Ch1);
		}

		while(vexRT(Btn6U) == false){
			;
		}

		while(vexRT(Btn6U) == true){
			;
			motor[port2] = vexRT(Ch2);
		}
		while(vexRT(Btn6U) == false){
			;
		}
		while(vexRT(Btn6U) == true){
			;
			motor[port2] = vexRT(Ch3);
		}
		while(vexRT(Btn6U) == false){
			;
		}
		while(vexRT(Btn6U) == true){
			;
			motor[port2] = vexRT(Ch4);
		}

	}
	*/
	while(true){
		motor[port1] = 127;
		motor[port2] = 127;
		motor[port3] = 127;
		motor[port4] = 127;
		motor[port5] = 127;
		motor[port6] = 127;
		motor[port7] = 127;
		motor[port8] = 127;
		motor[port9] = 127;
		motor[port10] = 127;
		a = SensorValue[in1];
		b = SensorValue[in2];
		c = SensorValue[in3];
		d = SensorValue[in4];
		e = SensorValue[in5];
		f = SensorValue[in6];
		g = SensorValue[in7];
		q = SensorValue[in8];
		batt = nImmediateBatteryLevel;
		wait1Msec(500);
		a = SensorValue[in1];
		b = SensorValue[in2];
		c = SensorValue[in3];
		d = SensorValue[in4];
		e = SensorValue[in5];
		f = SensorValue[in6];
		g = SensorValue[in7];
		q = SensorValue[in8];
		batt = nImmediateBatteryLevel;
		wait1Msec(500);
		motor[port1] = -127;
		motor[port2] = -127;
		motor[port3] = -127;
		motor[port4] = -127;
		motor[port5] = -127;
		motor[port6] = -127;
		motor[port7] = -127;
		motor[port8] = -127;
		motor[port9] = -127;
		motor[port10] = -127;
		a = SensorValue[in1];
		b = SensorValue[in2];
		c = SensorValue[in3];
		d = SensorValue[in4];
		e = SensorValue[in5];
		f = SensorValue[in6];
		g = SensorValue[in7];
		q = SensorValue[in8];
		batt = nImmediateBatteryLevel;
		wait1Msec(500);
		a = SensorValue[in1];
		b = SensorValue[in2];
		c = SensorValue[in3];
		d = SensorValue[in4];
		e = SensorValue[in5];
		f = SensorValue[in6];
		g = SensorValue[in7];
		q = SensorValue[in8];
		batt = nImmediateBatteryLevel;
		wait1Msec(500);
	}
}
