#pragma config(Motor,  port1,           drivemotor1,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          drivemotor2,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		//joystick control
		motor[port1] = vexRT(Ch3);
		motor[port10] = vexRT(Ch2);

		if(vexRT(Btn6U)){
			motor[port7] = -100;
		}
		else if(vexRT(Btn6D)){
			motor[port7] = 70;
		} else {
			motor[port7] = 0;
		}
		if(vexRT(Btn8R)){
			motor[port6] = -127;
		} else if(vexRT(Btn8L)){
			motor[port6] = 0;
		}

	}
}
